# Site settings
title: Drumlogue Units
description: Custom DSP units for the Korg drumlogue drum machine, featuring high-quality effects and synthesizers inspired by Mutable Instruments.
baseurl: "/drumlogue-units"
url: "https://cldmnky.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
